name: Dismiss Stale PR Reviews

on:
  pull_request_target:
    types: [opened, synchronize, reopened]

permissions:
  actions: read
  contents: read
  pull-requests: write

jobs:
  dismiss-stale-approvals:
    runs-on: ubuntu-latest
    steps:
      - name: Dismiss Stale PR Reviews
        if: ${{ !contains('OWNER,MEMBER,COLLABORATOR', github.event.pull_request.author_association) }}
        uses: withgraphite/dismiss-stale-approvals@36620714c84092b9d1bd5123ab3b5e11c48b5119
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
